name: Matrix
on: pull_request

jobs:
    node-version:
        strategy:
          matrix:
            os: [macos-latest, ubuntu-latest, windows-latests]
            node_version: [6,8,10]
            exclude:
                - os: ubuntu-latest
                  node_version: 6
                - os: macos-latest
                  node_version: 8A
        runs-on: ${{ matrix.os }}
        steps:
            - name: Log node version
              run: node -v
            - uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node_version }}
            - name: Log node version
              run: node -v